import type {
  CoffeeOrderItemStatus,
  CoffeeOrderStatus,
  CoffeePaymentMethod,
  CoffeePaymentStatus,
  CoffeePreparationWorkspace,
  CoffeeTableOperationalStatus,
} from './bar-domain';
import type { CoffeeBarOperationError } from './bar-repository-contracts';

export const coffeeBarRu = {
  eyebrow: 'Рабочее пространство',
  title: 'Бар',
  hall: 'Зал',
  menu: 'Меню',
  orders: 'Заказы',
  activeEmployee: 'Сотрудник',
  changeEmployee: 'Сменить сотрудника',
  location: 'Локация',
  establishment: 'Заведение',
  newOrder: 'Новый заказ',
  floorPlan: 'План зала',
  zones: 'Зоны',
  tableHint: 'Нажмите свободный стол, чтобы посадить гостей.',
  order: 'Заказ',
  takeaway: 'Навынос',
  table: 'Стол',
  guestCount: 'Количество гостей',
  seatingNote: 'Комментарий к посадке',
  capacityOverride: 'Посадить сверх вместимости',
  seatGuests: 'Открыть стол',
  changeGuests: 'Изменить гостей',
  transfer: 'Перенести заказ',
  attach: 'Прикрепить заказ',
  attachToTable: 'Прикрепить к столу',
  attachAsTakeaway: 'Оформить навынос',
  releaseTable: 'Освободить пустой стол',
  searchProducts: 'Поиск по меню',
  allCategories: 'Все',
  noProducts: 'Позиции не найдены.',
  add: 'Добавить',
  addItems: 'Добавить позиции',
  additional: 'Дополнительно',
  composition: 'Чек',
  submitted: 'Уже отправлено',
  newItems: 'Новые позиции',
  emptyOrder: 'Добавьте хотя бы одну позицию.',
  quantity: 'Количество',
  remove: 'Удалить',
  edit: 'Изменить',
  comment: 'Комментарий',
  commentPlaceholder: 'Например: без сахара',
  send: 'Отправить в работу',
  sendAdditional: 'Отправить дополнение',
  cancel: 'Отменить заказ',
  cancellationReason: 'Причина отмены',
  payment: 'Отметить оплату',
  paymentNotice: 'Локальная отметка прототипа. Реальная оплата не проводится.',
  cash: 'Наличные',
  card: 'Карта',
  preparation: 'Приготовление',
  accept: 'Принять',
  acceptAll: 'Принять всё',
  ready: 'Готов',
  allReady: 'Всё готово',
  total: 'Итого',
  ruble: '₽',
  loading: 'Загружаем рабочее пространство…',
  accessDenied: 'Нет доступа к рабочему пространству «Бар».',
  retry: 'Повторить',
  selectOrder: 'Выберите стол или создайте заказ навынос.',
  immutableNotice: 'Отправленную позицию изменять нельзя.',
  routingBar: 'Готовит бар',
  routingKitchen: 'Передано на кухню',
  routingImmediate: 'Готово сразу',
  success: 'Изменения сохранены.',
  error: 'Не удалось выполнить действие.',
  completedAt: 'Завершён',
  history: 'История',
  journal: 'Журнал заказов',
  searchOrders: 'Найти по номеру',
  filterAll: 'Все',
  filterActive: 'Активные',
  filterTakeaway: 'Навынос',
  filterDelivery: 'Доставка',
  filterReady: 'Готовые',
  filterCompleted: 'Завершённые',
  filterCancelled: 'Отменённые',
  noOrders: 'Заказы не найдены.',
  emptyOrderPreview: 'Позиции не добавлены',
  moreItems: (count: number) => `+ ещё ${count} позиций`,
  requiredOption: 'Выберите обязательный вариант',
  optionalOption: 'Необязательный выбор',
  maximumOptions: (count: number) => `Можно выбрать до ${count}`,
  noTables: 'Для выбранной локации столы не настроены.',
} as const;

export const coffeeOrderStatusRu: Record<CoffeeOrderStatus, string> = {
  DRAFT: 'Черновик',
  SENT: 'Отправлен',
  IN_PREPARATION: 'Готовится',
  READY: 'Готов',
  COMPLETED: 'Завершён',
  CANCELLED: 'Отменён',
};

export const coffeeOrderItemStatusRu: Record<CoffeeOrderItemStatus, string> = {
  DRAFT: 'Черновик',
  NEW: 'Новый',
  PREPARING: 'Готовится',
  READY: 'Готов',
  CANCELLED: 'Отменён',
};

export const coffeePaymentStatusRu: Record<CoffeePaymentStatus, string> = {
  UNPAID: 'Не оплачен',
  PAID: 'Оплачен',
};

export const coffeePaymentMethodRu: Record<CoffeePaymentMethod, string> = {
  CASH: coffeeBarRu.cash,
  CARD: coffeeBarRu.card,
};

export const coffeeTableStatusRu: Record<CoffeeTableOperationalStatus, string> = {
  FREE: 'Свободен',
  OCCUPIED: 'Посажены гости',
  DRAFT: 'Новый заказ',
  SENT: 'Отправлен',
  IN_PREPARATION: 'Готовится',
  READY: 'Готов',
  PAID: 'Оплачен',
  AWAITING_COMPLETION: 'Ждёт завершения',
};

export const coffeePreparationWorkspaceRu: Record<CoffeePreparationWorkspace, string> =
  {
    BAR: coffeeBarRu.routingBar,
    KITCHEN: coffeeBarRu.routingKitchen,
    IMMEDIATE: coffeeBarRu.routingImmediate,
  };

export const coffeeBarErrorRu: Record<CoffeeBarOperationError['code'], string> = {
  ACCESS_DENIED: coffeeBarRu.accessDenied,
  NOT_FOUND: 'Запрошенные данные не найдены.',
  INVALID_OPERATION: 'Это действие недоступно в текущем состоянии заказа.',
  TABLE_OCCUPIED: 'У этого стола уже есть открытый заказ.',
  ORDER_EMPTY: 'Нет новых позиций для отправки.',
  ORDER_IMMUTABLE: coffeeBarRu.immutableNotice,
  ITEM_ROUTE_MISMATCH: 'Эта позиция готовится в другом рабочем пространстве.',
  PAYMENT_REQUIRED: 'Перед завершением отметьте оплату.',
  ORDER_NOT_READY: 'Все позиции должны быть готовы.',
  CAPACITY_EXCEEDED: 'Количество гостей превышает вместимость стола.',
  INVALID_MODIFIERS: 'Проверьте обязательные модификаторы и ограничения выбора.',
  PAYMENT_ALREADY_RECORDED: 'Оплата уже отмечена.',
  CANCELLATION_REASON_REQUIRED: 'Укажите причину отмены отправленного заказа.',
  TABLE_NOT_FREE: 'Выбранный стол занят.',
};
