import type {
  CoffeeDevelopmentSeed,
  CoffeeFloorPlanZone,
  CoffeeLocation,
  CoffeeTable,
  Employee,
  Ingredient,
  MenuItem,
  ModifierGroup,
  Recipe,
  Supplier,
  UnitOfMeasure,
  Warehouse,
} from './domain';
import { recipeNetQuantity } from './recipe-migration';

export const coffeeCrashTestSeedVersion = 5;
export const coffeeCrashTestSeedId = `coffee-crash-test-v${coffeeCrashTestSeedVersion}`;

const active = 'active' as const;

function units(timestamp: string): UnitOfMeasure[] {
  return [
    ['kg', 'Килограмм', 'кг', 'mass', 'unit-g', 1000],
    ['g', 'Грамм', 'г', 'mass', '', 1],
    ['l', 'Литр', 'л', 'volume', 'unit-ml', 1000],
    ['ml', 'Миллилитр', 'мл', 'volume', '', 1],
    ['pc', 'Штука', 'шт', 'count', '', 1],
    ['package', 'Упаковка', 'упак', 'count', 'unit-pc', 50],
    ['bottle', 'Бутылка', 'бут', 'count', 'unit-pc', 1],
    ['portion', 'Порция', 'порц', 'count', 'unit-pc', 1],
  ].map(([id, name, symbol, dimension, target, rate]) => ({
    id: `unit-${id}`,
    name: name as string,
    symbol: symbol as string,
    dimension: dimension as string,
    conversionTargetId: target as string,
    conversionRate: rate as number,
    status: active,
    updatedAt: timestamp,
  }));
}

function locations(timestamp: string): CoffeeLocation[] {
  return [
    {
      id: 'crash-location-main',
      name: 'Север Coffee Lab — основная кофейня',
      code: 'SCL-MAIN',
      locationType: 'cafe',
      address: 'Россия, Москва, ул. Тверская, д. 12',
      timezone: 'Europe/Moscow',
      currency: 'RUB',
      phone: '+7 495 555-12-12',
      email: 'manager@sever-coffee.test',
      openingHours: 'Пн–Вс 07:30–23:00',
      isDefault: true,
      operationalPurpose: 'Продажи, бар, обслуживание гостей',
      status: active,
      updatedAt: timestamp,
    },
    {
      id: 'crash-location-production',
      name: 'Производственная зона',
      code: 'SCL-PROD',
      locationType: 'production',
      address: 'Основная кофейня · служебная зона',
      timezone: 'Europe/Moscow',
      currency: 'RUB',
      phone: '+7 495 555-12-13',
      email: 'production@sever-coffee.test',
      openingHours: 'Пн–Вс 06:30–22:00',
      isDefault: false,
      operationalPurpose: 'Кухня, сборка и подготовка продукции',
      status: active,
      updatedAt: timestamp,
    },
  ];
}

function floorPlanZones(timestamp: string): CoffeeFloorPlanZone[] {
  return [
    {
      id: 'crash-zone-main',
      locationId: 'crash-location-main',
      name: 'Основной зал',
      zoneType: 'MAIN_HALL',
      canvasWidth: 800,
      canvasHeight: 500,
      active: true,
      sortOrder: 1,
      updatedAt: timestamp,
    },
    {
      id: 'crash-zone-street',
      locationId: 'crash-location-main',
      name: 'Улица',
      zoneType: 'STREET',
      canvasWidth: 800,
      canvasHeight: 500,
      active: true,
      sortOrder: 2,
      updatedAt: timestamp,
    },
  ];
}

function tables(timestamp: string): CoffeeTable[] {
  return Array.from({ length: 12 }, (_, index) => ({
    id: `crash-table-${String(index + 1).padStart(2, '0')}`,
    name: `Стол ${index + 1}`,
    code: `T-${String(index + 1).padStart(2, '0')}`,
    zoneId: index < 8 ? 'crash-zone-main' : 'crash-zone-street',
    shape:
      index % 4 === 0
        ? 'ROUND'
        : index % 4 === 1
          ? 'SQUARE'
          : index % 4 === 2
            ? 'RECTANGLE'
            : 'BAR_SEAT',
    positionX: 60 + (index % 4) * 175,
    positionY: 65 + (Math.floor(index / 4) % 2) * 190,
    width: index % 4 === 2 ? 150 : index % 4 === 3 ? 80 : 110,
    height: index % 4 === 2 ? 90 : index % 4 === 3 ? 60 : 110,
    rotation: index % 4 === 2 ? 0 : 0,
    seatCount: index < 4 ? 2 : index < 10 ? 4 : 6,
    sortOrder: index + 1,
    locationId: 'crash-location-main',
    status: active,
    updatedAt: timestamp,
  }));
}

function warehouses(timestamp: string): Warehouse[] {
  return [
    ['main', 'Главный склад', 'WH-MAIN', 'storage', 'Складская комната', true],
    ['bar', 'Барный запас', 'WH-BAR', 'bar', 'Барная стойка', false],
    [
      'kitchen',
      'Кухонный запас',
      'WH-KITCHEN',
      'kitchen',
      'Производственная зона',
      false,
    ],
    ['waste', 'Зона списаний', 'WH-WASTE', 'waste', 'Изолированная зона брака', false],
  ].map(([id, name, code, type, zone, isDefault]) => ({
    id: `crash-warehouse-${id}`,
    name: name as string,
    code: code as string,
    locationId: id === 'kitchen' ? 'crash-location-production' : 'crash-location-main',
    warehouseType: type as string,
    addressOrZone: zone as string,
    responsibleEmployeeId: 'crash-employee-warehouse',
    isDefault: isDefault as boolean,
    operationalPurpose:
      id === 'waste' ? 'Учёт брака и будущих списаний' : 'Хранение активных запасов',
    status: active,
    updatedAt: timestamp,
  }));
}

function suppliers(timestamp: string): Supplier[] {
  const specifications: Array<
    [string, string, string, string, string, string, string, string, string]
  > = [
    [
      'beans',
      'Северное зерно',
      'SUP-COFFEE',
      'Анна Орлова',
      '+7 495 100-10-01',
      'coffee@demo-supply.test',
      '7712345001',
      'Кофе, чай, какао',
      '14 календарных дней',
    ],
    [
      'dairy',
      'Молочная линия',
      'SUP-DAIRY',
      'Илья Волков',
      '+7 495 100-10-02',
      'dairy@demo-supply.test',
      '7712345002',
      'Молоко, сливки, альтернативное молоко',
      '7 календарных дней',
    ],
    [
      'syrup',
      'Барный вкус',
      'SUP-SYRUP',
      'Мария Соколова',
      '+7 495 100-10-03',
      'syrup@demo-supply.test',
      '7712345003',
      'Сиропы, соусы, напитки',
      'Предоплата 50%',
    ],
    [
      'food',
      'Городская пекарня',
      'SUP-FOOD',
      'Павел Морозов',
      '+7 495 100-10-04',
      'food@demo-supply.test',
      '7712345004',
      'Выпечка, сэндвичи, десерты',
      '7 календарных дней',
    ],
    [
      'packaging',
      'Чистая упаковка',
      'SUP-PACK',
      'Ольга Лебедева',
      '+7 495 100-10-05',
      'pack@demo-supply.test',
      '7712345005',
      'Стаканы, крышки, салфетки, расходники',
      '21 календарный день',
    ],
  ];
  return specifications.map(
    ([
      id,
      name,
      supplierCode,
      contactPerson,
      phone,
      email,
      taxIdentifier,
      suppliedIngredients,
      paymentTerms,
    ]) => ({
      id: `crash-supplier-${id}`,
      name,
      supplierCode,
      contactPerson,
      phone,
      email,
      address: 'Россия, Москва',
      taxIdentifier,
      paymentTerms,
      deliverySchedule: 'По будням 06:00–10:00',
      suppliedIngredients,
      status: active,
      updatedAt: timestamp,
    }),
  );
}

type IngredientSpec = [
  id: string,
  name: string,
  category: string,
  unit: string,
  purchaseUnit: string,
  conversion: number,
  minimum: number,
  cost: number,
  supplier: string,
  warehouse: string,
];

const ingredientSpecs: IngredientSpec[] = [
  [
    'espresso-beans',
    'Зерно для эспрессо',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    5000,
    1.8,
    'beans',
    'bar',
  ],
  [
    'filter-beans',
    'Зерно для фильтра',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    3000,
    2.1,
    'beans',
    'bar',
  ],
  [
    'decaf-beans',
    'Кофе без кофеина',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    1000,
    2.4,
    'beans',
    'bar',
  ],
  [
    'black-tea',
    'Чёрный чай',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    500,
    1.1,
    'beans',
    'bar',
  ],
  [
    'green-tea',
    'Зелёный чай',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    500,
    1.25,
    'beans',
    'bar',
  ],
  [
    'cocoa',
    'Какао-порошок',
    'Кофе и напитки',
    'g',
    'kg',
    1000,
    1000,
    0.9,
    'beans',
    'bar',
  ],
  [
    'water',
    'Вода питьевая',
    'Кофе и напитки',
    'bottle',
    'package',
    12,
    24,
    45,
    'syrup',
    'main',
  ],
  [
    'sparkling-water',
    'Вода газированная',
    'Кофе и напитки',
    'bottle',
    'package',
    12,
    24,
    52,
    'syrup',
    'main',
  ],
  [
    'whole-milk',
    'Молоко 3,2%',
    'Молочная продукция',
    'ml',
    'l',
    1000,
    12000,
    0.105,
    'dairy',
    'bar',
  ],
  [
    'lactose-free-milk',
    'Молоко безлактозное',
    'Молочная продукция',
    'ml',
    'l',
    1000,
    4000,
    0.145,
    'dairy',
    'bar',
  ],
  [
    'oat-milk',
    'Молоко овсяное',
    'Молочная продукция',
    'ml',
    'l',
    1000,
    6000,
    0.19,
    'dairy',
    'bar',
  ],
  [
    'cream',
    'Сливки 10%',
    'Молочная продукция',
    'ml',
    'l',
    1000,
    3000,
    0.22,
    'dairy',
    'bar',
  ],
  ['sugar', 'Сахар', 'Добавки', 'g', 'kg', 1000, 5000, 0.09, 'syrup', 'bar'],
  [
    'vanilla-syrup',
    'Сироп ванильный',
    'Добавки',
    'ml',
    'bottle',
    1000,
    1500,
    0.65,
    'syrup',
    'bar',
  ],
  [
    'caramel-syrup',
    'Сироп карамельный',
    'Добавки',
    'ml',
    'bottle',
    1000,
    1500,
    0.68,
    'syrup',
    'bar',
  ],
  [
    'hazelnut-syrup',
    'Сироп лесной орех',
    'Добавки',
    'ml',
    'bottle',
    1000,
    1000,
    0.72,
    'syrup',
    'bar',
  ],
  [
    'chocolate-sauce',
    'Соус шоколадный',
    'Добавки',
    'ml',
    'bottle',
    1000,
    1000,
    0.78,
    'syrup',
    'bar',
  ],
  ['cinnamon', 'Корица', 'Добавки', 'g', 'package', 250, 250, 0.45, 'syrup', 'bar'],
  [
    'croissant',
    'Круассан классический',
    'Еда',
    'pc',
    'package',
    20,
    12,
    75,
    'food',
    'kitchen',
  ],
  [
    'sandwich-bread',
    'Хлеб для сэндвича',
    'Еда',
    'pc',
    'package',
    24,
    20,
    28,
    'food',
    'kitchen',
  ],
  ['ham', 'Ветчина', 'Еда', 'g', 'kg', 1000, 1500, 0.82, 'food', 'kitchen'],
  ['cheese', 'Сыр', 'Еда', 'g', 'kg', 1000, 1500, 0.95, 'food', 'kitchen'],
  ['lettuce', 'Салат листовой', 'Еда', 'g', 'kg', 1000, 500, 0.4, 'food', 'kitchen'],
  [
    'dessert',
    'Десерт шоколадный',
    'Еда',
    'pc',
    'package',
    12,
    8,
    110,
    'food',
    'kitchen',
  ],
  [
    'cup-small',
    'Стакан 200 мл',
    'Расходники',
    'pc',
    'package',
    50,
    200,
    7,
    'packaging',
    'main',
  ],
  [
    'cup-medium',
    'Стакан 300 мл',
    'Расходники',
    'pc',
    'package',
    50,
    300,
    8,
    'packaging',
    'main',
  ],
  [
    'cup-large',
    'Стакан 400 мл',
    'Расходники',
    'pc',
    'package',
    50,
    200,
    9,
    'packaging',
    'main',
  ],
  [
    'lid-small',
    'Крышка 200 мл',
    'Расходники',
    'pc',
    'package',
    50,
    200,
    4,
    'packaging',
    'main',
  ],
  [
    'lid-medium',
    'Крышка 300 мл',
    'Расходники',
    'pc',
    'package',
    50,
    300,
    4.5,
    'packaging',
    'main',
  ],
  [
    'lid-large',
    'Крышка 400 мл',
    'Расходники',
    'pc',
    'package',
    50,
    200,
    5,
    'packaging',
    'main',
  ],
  [
    'sleeve',
    'Манжета для стакана',
    'Расходники',
    'pc',
    'package',
    100,
    200,
    3.5,
    'packaging',
    'main',
  ],
  [
    'napkin',
    'Салфетка',
    'Расходники',
    'pc',
    'package',
    500,
    1000,
    0.7,
    'packaging',
    'main',
  ],
  [
    'bag',
    'Пакет навынос',
    'Расходники',
    'pc',
    'package',
    100,
    100,
    7.5,
    'packaging',
    'main',
  ],
  [
    'stirrer',
    'Размешиватель',
    'Расходники',
    'pc',
    'package',
    500,
    500,
    0.6,
    'packaging',
    'main',
  ],
  [
    'cleaner',
    'Средство для кофемашины',
    'Хозяйственные товары',
    'g',
    'package',
    1000,
    500,
    1.3,
    'packaging',
    'main',
  ],
  [
    'filter-paper',
    'Фильтр бумажный',
    'Расходники',
    'pc',
    'package',
    100,
    100,
    2.2,
    'packaging',
    'bar',
  ],
];

function ingredients(timestamp: string): Ingredient[] {
  return ingredientSpecs.map(
    ([
      id,
      name,
      category,
      unit,
      purchaseUnit,
      conversionRate,
      minimumStock,
      cost,
      supplier,
      warehouse,
    ]) => ({
      id: `crash-ingredient-${id}`,
      name,
      sku: `INV-${id.toUpperCase()}`,
      category,
      baseUnitId: `unit-${unit}`,
      purchaseUnitId: `unit-${purchaseUnit}`,
      conversionRate,
      minimumStock,
      reorderQuantity: Math.max(minimumStock * 2, 10),
      cost,
      preferredSupplierId: `crash-supplier-${supplier}`,
      supplierReferences: `crash-supplier-${supplier}`,
      storageLocationId: `crash-warehouse-${warehouse}`,
      status: active,
      updatedAt: timestamp,
    }),
  );
}

const productSpecs = [
  ['espresso', 'Эспрессо', 'coffee', 190],
  ['double-espresso', 'Двойной эспрессо', 'coffee', 260],
  ['americano', 'Американо', 'coffee', 230],
  ['cappuccino', 'Капучино', 'coffee', 310],
  ['latte', 'Латте', 'coffee', 340],
  ['flat-white', 'Флэт уайт', 'coffee', 350],
  ['raf', 'Раф', 'coffee', 390],
  ['mocha', 'Мокка', 'coffee', 380],
  ['filter-coffee', 'Фильтр-кофе', 'coffee', 270],
  ['decaf-cappuccino', 'Капучино без кофеина', 'coffee', 350],
  ['black-tea', 'Чёрный чай', 'tea', 220],
  ['green-tea', 'Зелёный чай', 'tea', 230],
  ['cocoa', 'Какао', 'other', 300],
  ['bottled-water', 'Вода без газа', 'other', 140],
  ['sparkling-water', 'Вода газированная', 'other', 160],
  ['croissant', 'Круассан', 'food', 230],
  ['sandwich', 'Сэндвич с ветчиной и сыром', 'food', 420],
  ['dessert', 'Шоколадный десерт', 'food', 360],
  ['iced-latte', 'Айс-латте', 'coffee', 370],
  ['vanilla-latte', 'Ванильный латте', 'coffee', 390],
  ['caramel-cappuccino', 'Карамельный капучино', 'coffee', 370],
  ['espresso-tonic-preview', 'Эспрессо-тоник · preview', 'other', 410],
] as const;

function menuItems(timestamp: string): MenuItem[] {
  const modifierGroupsByProduct: Record<string, string[]> = {
    espresso: ['espresso-volume', 'extra-shot', 'coffee-additional'],
    'double-espresso': ['espresso-volume', 'coffee-additional'],
    americano: ['coffee-volume', 'extra-shot', 'coffee-additional'],
    cappuccino: ['coffee-volume', 'milk', 'syrup', 'extra-shot', 'coffee-additional'],
    latte: ['coffee-volume', 'milk', 'syrup', 'coffee-additional'],
    'flat-white': ['coffee-volume', 'milk', 'extra-shot', 'coffee-additional'],
    raf: ['coffee-volume', 'syrup', 'coffee-additional'],
    mocha: ['coffee-volume', 'milk', 'syrup', 'coffee-additional'],
    'filter-coffee': ['coffee-volume', 'coffee-additional'],
    'decaf-cappuccino': ['coffee-volume', 'milk', 'syrup', 'coffee-additional'],
    'black-tea': ['tea-volume', 'tea-additional'],
    'green-tea': ['tea-volume', 'tea-additional'],
    cocoa: ['coffee-volume', 'milk', 'coffee-additional'],
    'iced-latte': ['coffee-volume', 'milk', 'syrup', 'coffee-additional'],
    'vanilla-latte': ['coffee-volume', 'milk', 'coffee-additional'],
    'caramel-cappuccino': ['coffee-volume', 'milk', 'coffee-additional'],
  };
  return productSpecs.map(([id, name, category, price]) => ({
    id: `crash-item-${id}`,
    name,
    categoryId: `crash-category-${category}`,
    description: 'CRASH TEST · подготовленная демонстрационная позиция',
    sku: `SALE-${id.toUpperCase()}`,
    barcode: '',
    sellingPrice: price,
    currency: 'RUB',
    taxCategory: 'standard',
    locationAvailability: 'Север Coffee Lab — CRASH TEST',
    preparationLocationId:
      category === 'food' ? 'crash-location-production' : 'crash-location-main',
    servingUnitId: 'unit-portion',
    imageAssetId: null,
    recipeId: [
      'bottled-water',
      'sparkling-water',
      'dessert',
      'espresso-tonic-preview',
    ].includes(id)
      ? ''
      : `crash-recipe-${id}`,
    modifierGroupIds: (modifierGroupsByProduct[id] ?? []).map(
      (groupId) => `crash-modifier-${groupId}`,
    ),
    status: id === 'espresso-tonic-preview' ? 'draft' : active,
    updatedAt: timestamp,
  }));
}

function modifierGroups(timestamp: string): ModifierGroup[] {
  const definitions: Array<Omit<ModifierGroup, 'status' | 'updatedAt'>> = [
    {
      id: 'crash-modifier-espresso-volume',
      name: 'Объём',
      purpose: 'configuration',
      selectionType: 'single',
      required: true,
      minimumSelections: 1,
      maximumSelections: 1,
      options: '30 мл; 60 мл +90 ₽',
    },
    {
      id: 'crash-modifier-coffee-volume',
      name: 'Объём',
      purpose: 'configuration',
      selectionType: 'single',
      required: true,
      minimumSelections: 1,
      maximumSelections: 1,
      options: '250 мл; 350 мл +70 ₽',
    },
    {
      id: 'crash-modifier-milk',
      name: 'Молоко',
      purpose: 'configuration',
      selectionType: 'single',
      required: false,
      minimumSelections: 0,
      maximumSelections: 1,
      options: 'Обычное; Овсяное +70 ₽; Безлактозное +50 ₽',
      consumptionEffects: [
        {
          optionName: 'Овсяное +70 ₽',
          mode: 'replace',
          resourceId: 'crash-ingredient-oat-milk',
          resourceType: 'ingredient',
          quantity: 180,
          unitId: 'unit-ml',
          replacesResourceId: 'crash-ingredient-whole-milk',
        },
        {
          optionName: 'Безлактозное +50 ₽',
          mode: 'replace',
          resourceId: 'crash-ingredient-lactose-free-milk',
          resourceType: 'ingredient',
          quantity: 180,
          unitId: 'unit-ml',
          replacesResourceId: 'crash-ingredient-whole-milk',
        },
      ],
    },
    {
      id: 'crash-modifier-syrup',
      name: 'Сироп',
      purpose: 'configuration',
      selectionType: 'single',
      required: false,
      minimumSelections: 0,
      maximumSelections: 1,
      options: 'Ванильный +50 ₽; Карамельный +50 ₽',
      consumptionEffects: [
        {
          optionName: 'Ванильный +50 ₽',
          mode: 'add',
          resourceId: 'crash-ingredient-vanilla-syrup',
          resourceType: 'ingredient',
          quantity: 20,
          unitId: 'unit-ml',
        },
        {
          optionName: 'Карамельный +50 ₽',
          mode: 'add',
          resourceId: 'crash-ingredient-caramel-syrup',
          resourceType: 'ingredient',
          quantity: 20,
          unitId: 'unit-ml',
        },
      ],
    },
    {
      id: 'crash-modifier-extra-shot',
      name: 'Дополнительный шот',
      purpose: 'configuration',
      selectionType: 'single',
      required: false,
      minimumSelections: 0,
      maximumSelections: 1,
      options: '1 шот +90 ₽; 2 шота +180 ₽',
      consumptionEffects: [
        {
          optionName: '1 шот +90 ₽',
          mode: 'add',
          resourceId: 'crash-ingredient-espresso-beans',
          resourceType: 'ingredient',
          quantity: 18,
          unitId: 'unit-g',
        },
        {
          optionName: '2 шота +180 ₽',
          mode: 'add',
          resourceId: 'crash-ingredient-espresso-beans',
          resourceType: 'ingredient',
          quantity: 36,
          unitId: 'unit-g',
        },
      ],
    },
    {
      id: 'crash-modifier-coffee-additional',
      name: 'Дополнительно',
      purpose: 'additional',
      selectionType: 'multiple',
      required: false,
      minimumSelections: 0,
      maximumSelections: 4,
      options: 'Сахар; Корица; Сливки +60 ₽; Маршмеллоу +50 ₽',
    },
    {
      id: 'crash-modifier-tea-volume',
      name: 'Объём',
      purpose: 'configuration',
      selectionType: 'single',
      required: true,
      minimumSelections: 1,
      maximumSelections: 1,
      options: '400 мл; 600 мл +80 ₽',
    },
    {
      id: 'crash-modifier-tea-additional',
      name: 'Дополнительно',
      purpose: 'additional',
      selectionType: 'multiple',
      required: false,
      minimumSelections: 0,
      maximumSelections: 2,
      options: 'Мёд +40 ₽; Лимон +30 ₽',
    },
  ];
  return definitions.map((definition) => ({
    ...definition,
    status: active,
    updatedAt: timestamp,
  }));
}

const recipeSpecs = [
  [
    'espresso',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['water', 1, 'bottle'],
    ],
    38,
  ],
  ['double-espresso', 1, [['espresso-beans', 36, 'g']], 68],
  ['americano', 1, [['espresso-beans', 18, 'g']], 38],
  [
    'cappuccino',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 180, 'ml'],
    ],
    57,
  ],
  [
    'latte',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 250, 'ml'],
    ],
    65,
  ],
  [
    'flat-white',
    1,
    [
      ['espresso-beans', 36, 'g'],
      ['whole-milk', 160, 'ml'],
    ],
    82,
  ],
  [
    'raf',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['cream', 180, 'ml'],
      ['vanilla-syrup', 20, 'ml'],
    ],
    87,
  ],
  [
    'mocha',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 180, 'ml'],
      ['chocolate-sauce', 25, 'ml'],
    ],
    76,
  ],
  [
    'filter-coffee',
    1,
    [
      ['filter-beans', 22, 'g'],
      ['filter-paper', 1, 'pc'],
    ],
    49,
  ],
  [
    'decaf-cappuccino',
    1,
    [
      ['decaf-beans', 18, 'g'],
      ['whole-milk', 180, 'ml'],
    ],
    68,
  ],
  [
    'black-tea',
    1,
    [
      ['black-tea', 5, 'g'],
      ['water', 1, 'bottle'],
    ],
    12,
  ],
  [
    'green-tea',
    1,
    [
      ['green-tea', 5, 'g'],
      ['water', 1, 'bottle'],
    ],
    13,
  ],
  [
    'cocoa',
    1,
    [
      ['cocoa', 25, 'g'],
      ['whole-milk', 220, 'ml'],
      ['sugar', 10, 'g'],
    ],
    48,
  ],
  ['croissant', 1, [['croissant', 1, 'pc']], 75],
  [
    'sandwich',
    1,
    [
      ['sandwich-bread', 2, 'pc'],
      ['ham', 60, 'g'],
      ['cheese', 40, 'g'],
      ['lettuce', 20, 'g'],
    ],
    152,
  ],
  [
    'iced-latte',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 220, 'ml'],
    ],
    62,
  ],
  [
    'vanilla-latte',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 230, 'ml'],
      ['vanilla-syrup', 20, 'ml'],
    ],
    78,
  ],
  [
    'caramel-cappuccino',
    1,
    [
      ['espresso-beans', 18, 'g'],
      ['whole-milk', 180, 'ml'],
      ['caramel-syrup', 20, 'ml'],
    ],
    71,
  ],
] as const;

function recipes(timestamp: string): Recipe[] {
  return recipeSpecs.map(([id, output, rows, cost]) => {
    const product = productSpecs.find(([productId]) => productId === id);
    const salePrice = product?.[3] ?? 0;
    const target = {
      type: 'menu-item' as const,
      id: `crash-item-${id}`,
      name: product?.[1] ?? id,
    };
    return {
      id: `crash-recipe-${id}`,
      name: `Техкарта · ${target.name}`,
      target,
      outputQuantity: output,
      outputUnitId: 'unit-portion',
      preparationInstructions:
        'Версия CRASH TEST. Выполнить стандартную последовательность приготовления.',
      components: rows.map(([ingredientId, quantity, unit], index) => ({
        id: `crash-component-${id}-${String(index + 1).padStart(2, '0')}`,
        type: 'ingredient' as const,
        referenceId: `crash-ingredient-${ingredientId}`,
        grossQuantity: quantity,
        unitId: `unit-${unit}`,
        lossPercentage: index === 0 ? 3 : 0,
        netQuantity: recipeNetQuantity(quantity, index === 0 ? 3 : 0),
      })),
      version: 1,
      effectiveDate: '2026-07-31',
      preparationLocationId:
        id === 'croissant' || id === 'sandwich'
          ? 'crash-location-production'
          : 'crash-location-main',
      calculatedCost: cost,
      salePrice,
      grossMargin:
        salePrice > 0 ? Number((((salePrice - cost) / salePrice) * 100).toFixed(1)) : 0,
      status: active,
      updatedAt: timestamp,
    };
  });
}

function employees(timestamp: string): Employee[] {
  return [
    [
      'owner',
      'Алексей Романов',
      'owner',
      ['crash-location-main', 'crash-location-production'],
    ],
    ['manager', 'Мария Воронцова', 'location-manager', ['crash-location-main']],
    ['barista', 'Иван Беляев', 'barista', ['crash-location-main']],
    ['cashier', 'Анна Лукина', 'cashier', ['crash-location-main']],
    [
      'warehouse',
      'Сергей Котов',
      'inventory',
      ['crash-location-main', 'crash-location-production'],
    ],
  ].map(([id, fullName, role, assignedLocationIds], index) => ({
    id: `crash-employee-${id}`,
    name: fullName as string,
    firstName: (fullName as string).split(' ')[0] ?? '',
    lastName: (fullName as string).split(' ').slice(1).join(' '),
    position:
      role === 'owner'
        ? 'Владелец'
        : role === 'location-manager'
          ? 'Менеджер'
          : role === 'barista'
            ? 'Бариста'
            : role === 'cashier'
              ? 'Кассир'
              : 'Кладовщик',
    fullName: fullName as string,
    email: `${id}@sever-coffee.test`,
    phone: `+7 999 555-20-0${index + 1}`,
    employeeCode: `EMP-${String(index + 1).padStart(3, '0')}`,
    assignedLocationIds: assignedLocationIds as string[],
    assignedRoleId: role as Employee['assignedRoleId'],
    employmentStatus: 'active',
    hireDate: '2026-01-15',
    notes: 'CRASH TEST · локальный демонстрационный профиль',
    status: active,
    updatedAt: timestamp,
  }));
}

export function createCoffeeCrashTestSeed(timestamp: string): CoffeeDevelopmentSeed {
  const inventory = ingredients(timestamp);
  const quantities: Record<string, number> = {
    'decaf-beans': 0,
    'hazelnut-syrup': 300,
    'espresso-beans': 18000,
    napkin: 6500,
    'chocolate-sauce': 5000,
  };
  return {
    id: coffeeCrashTestSeedId,
    projectDisplayName: 'Север Coffee Lab — CRASH TEST',
    locations: locations(timestamp),
    floorPlanZones: floorPlanZones(timestamp),
    tables: tables(timestamp),
    registers: [
      {
        id: 'crash-register-main',
        name: 'Основная касса',
        code: 'REG-01',
        locationId: 'crash-location-main',
        receiptPrinter: 'Demo receipt printer',
        cashDrawer: 'Demo cash drawer',
        paymentMethods: 'Наличные, карта, СБП',
        status: active,
        updatedAt: timestamp,
      },
    ],
    workstations: (
      [
        ['pos', 'Касса', 'crash-register-main', 'POS, Menu'],
        ['barista', 'Бариста', '', 'Bar, Recipes'],
        ['kitchen', 'Кухня', '', 'Kitchen, Recipes'],
        ['inventory', 'Склад', '', 'Inventory'],
        ['manager', 'Менеджер', '', 'Configuration, Reports'],
      ] satisfies Array<
        [
          'pos' | 'barista' | 'kitchen' | 'inventory' | 'manager',
          string,
          string,
          string,
        ]
      >
    ).map(([type, name, registerId, enabledModules]) => ({
      id: `crash-workstation-${type}`,
      name: `${name} · CRASH TEST`,
      workstationType: type as 'pos' | 'barista' | 'kitchen' | 'inventory' | 'manager',
      locationId:
        type === 'kitchen' ? 'crash-location-production' : 'crash-location-main',
      registerId,
      printer: type === 'kitchen' ? 'Demo kitchen printer' : '',
      enabledModules,
      status: active,
      updatedAt: timestamp,
    })),
    warehouses: warehouses(timestamp),
    units: units(timestamp),
    ingredients: inventory,
    menuCategories: [
      ['coffee', 'Кофе', 1],
      ['tea', 'Чай', 2],
      ['other', 'Другие напитки', 3],
      ['food', 'Еда и десерты', 4],
    ].map(([id, name, displayOrder]) => ({
      id: `crash-category-${id}`,
      name: name as string,
      description: 'CRASH TEST · активная категория',
      displayOrder: displayOrder as number,
      locationAvailability: 'Север Coffee Lab — CRASH TEST',
      imageAssetId: null,
      status: active,
      updatedAt: timestamp,
    })),
    menuItems: menuItems(timestamp),
    modifiers: modifierGroups(timestamp),
    recipes: recipes(timestamp),
    openingStockBalances: inventory.map((ingredient, index) => {
      const specId = ingredient.id.replace('crash-ingredient-', '');
      const quantity =
        quantities[specId] ??
        Math.max(
          ingredient.minimumStock * 3,
          ingredient.baseUnitId === 'unit-pc' ? 100 : 3000,
        );
      return {
        id: `crash-opening-${String(index + 1).padStart(2, '0')}`,
        warehouseId: ingredient.storageLocationId ?? 'crash-warehouse-main',
        ingredientId: ingredient.id,
        quantity,
        unitId: ingredient.baseUnitId,
        unitCost: ingredient.cost,
        source: 'development-demo',
        recordedAt: timestamp,
      };
    }),
    suppliers: suppliers(timestamp),
    employees: employees(timestamp),
  };
}
