import type { ManagerSection, ManagerWarningSeverity } from './domain';

export const managerRu = {
  locale: 'ru-RU',
  title: 'Управляющий',
  subtitle: 'Контроль работы без изменения данных операционных модулей',
  loading: 'Загружаем актуальные показатели…',
  loadError: 'Не удалось получить данные модулей. Обновите экран.',
  refresh: 'Обновить',
  logout: 'Сменить сотрудника',
  updated: 'Обновлено',
  noData: 'Нет данных',
  notConfigured: 'Не настроено',
  unavailable: 'Недоступно',
  warehouseUnavailable: 'Данные склада временно недоступны.',
  purchasingUnavailable: 'Данные закупок временно недоступны.',
  incompleteWarnings: 'Предупреждения показаны только по доступным источникам данных.',
  openWorkspace: 'Открыть рабочее пространство',
  ownerNavigationOnly:
    'Перейдите в соответствующее рабочее пространство на подключённом устройстве.',
  noWarnings: 'Актуальных предупреждений нет.',
  noEvents: 'Событий пока нет.',
  noOrders: 'Заказов поставщикам пока нет.',
  noDeliveries: 'Поставок пока нет.',
  noNeeds: 'Потребность в закупке не рассчитана.',
  noBalances: 'Складские остатки пока не настроены.',
  noMovements: 'Движений по складу пока нет.',
  revenueToday: 'Выручка сегодня',
  receiptsToday: 'Чеков сегодня',
  averageReceipt: 'Средний чек',
  activeOrders: 'Активные заказы',
  overdueOrders: 'Просроченные заказы',
  warningsCount: 'Предупреждения',
  thresholdsMissing: 'Минимум не настроен',
  noActiveOrders: 'Нет активных заказов',
  lowStock: 'Ниже минимума',
  outOfStock: 'Нет в наличии',
  priorityWarnings: 'Приоритетные предупреждения',
  recentEvents: 'Последние события',
  purchaseNeeds: 'Потребность',
  purchaseOrders: 'Заказы поставщикам',
  drafts: 'Черновики',
  sent: 'Отправленные',
  partiallyDelivered: 'Частично поставленные',
  deliveredOrders: 'Полностью поставленные',
  cancelledOrders: 'Отменённые',
  deliveries: 'Поставки',
  balances: 'Остатки',
  movements: 'Последние движения',
  issues: 'Проблемы конфигурации',
  supplier: 'Поставщик',
  warehouse: 'Склад',
  expected: 'Ожидается',
  actual: 'Фактически',
  recommended: 'Рекомендовано',
  recommendedPurchase: 'Рекомендовано к закупке',
  openOrderExists: 'Активный заказ создан',
  openOrderMissing: 'Активного заказа нет',
  status: 'Статус',
  source: 'Источник',
  sourceWarehouse: 'Склад',
  sourcePurchasing: 'Закупщик',
  action: 'Что сделать',
  quantity: 'Количество',
  minimum: 'Минимум',
  notSet: 'Не задано',
  sections: {
    overview: 'Обзор',
    purchasing: 'Контроль закупок',
    warehouse: 'Контроль склада',
    events: 'События',
    warnings: 'Предупреждения',
  } satisfies Record<ManagerSection, string>,
  severity: {
    info: 'Информация',
    warning: 'Требует внимания',
    critical: 'Критично',
  } satisfies Record<ManagerWarningSeverity, string>,
  orderStatus: {
    DRAFT: 'Черновик',
    SENT: 'Отправлен',
    PARTIALLY_DELIVERED: 'Частично поставлен',
    DELIVERED: 'Поставлен',
    CANCELLED: 'Отменён',
  },
  deliveryStatus: {
    DRAFT: 'Черновик',
    POSTED: 'Проведена',
    CANCELLED: 'Отменена',
  },
  balanceStatus: {
    IN_STOCK: 'В наличии',
    LOW: 'Ниже минимума',
    OUT_OF_STOCK: 'Нет в наличии',
    NEGATIVE: 'Отрицательный остаток',
  },
  units: {
    g: 'г',
    ml: 'мл',
    pc: 'шт.',
  },
} as const;

export const managerOrderStatusRu: Record<string, string> = {
  DRAFT: 'Черновик',
  SENT: 'Отправлен',
  PARTIALLY_DELIVERED: 'Частично поставлен',
  DELIVERED: 'Поставлен',
  CANCELLED: 'Отменён',
};

export const managerDeliveryStatusRu: Record<string, string> = {
  DRAFT: 'Черновик',
  POSTED: 'Проведена',
  CANCELLED: 'Отменена',
};

export const managerMovementTypeRu: Record<string, string> = {
  OPENING_BALANCE: 'Начальный остаток',
  RECEIPT: 'Приход',
  WRITE_OFF: 'Списание',
  TRANSFER_OUT: 'Перемещение со склада',
  TRANSFER_IN: 'Перемещение на склад',
  INVENTORY_SURPLUS: 'Излишек инвентаризации',
  INVENTORY_SHORTAGE: 'Недостача инвентаризации',
  SALE_CONSUMPTION: 'Расход по продаже',
  REVERSAL: 'Обратное движение',
};
