export const kitchenText = {
  title: 'Кухня',
  workspace: 'Рабочее пространство',
  new: 'Новые',
  preparing: 'Готовятся',
  ready: 'Готовые',
  history: 'История',
  accept: 'Принять',
  acceptAll: 'Принять всё',
  markReady: 'Готов',
  allReady: 'Всё готово',
  comment: 'Комментарий',
  instruction: 'Инструкция',
  waitingTime: 'Время ожидания',
  noNewOrders: 'Нет новых заказов',
  noPreparingOrders: 'Нет заказов в приготовлении',
  noReadyOrders: 'Нет готовых заказов',
  noHistory: 'История пока пуста',
  noData: 'Нет данных',
  inactiveOrder: 'Заказ больше не активен',
  recipeUnavailable: 'Рецептура недоступна',
  warehouseMissing: 'Склад кухни не настроен',
  ownerPreview: 'Предпросмотр владельца: действия приготовления недоступны.',
  loadError: 'Не удалось загрузить очередь. Попробуйте ещё раз.',
  actionError: 'Действие не выполнено. Данные очереди обновлены.',
  retry: 'Повторить',
  employee: 'Передал',
  responsible: 'Готовил',
  location: 'Локация',
  warehouse: 'Склад',
  notConfigured: 'Не настроено',
  byTime: 'По времени',
  byTable: 'По столу',
  logout: 'Сменить сотрудника',
  minutes: 'мин',
  completed: 'Подтверждено',
  sorting: 'Сортировка',
  loading: 'Загрузка очереди…',
  preparationDuration: 'Приготовление',
} as const;
